basePath: /
definitions:
  core.Item:
    properties:
      description:
        type: string
      id:
        type: string
      name:
        type: string
      nickname:
        type: string
      price:
        type: number
      site:
        type: string
      startTime:
        type: string
    type: object
host: 127.0.0.1:8888
info:
  contact: {}
  description: This is a microservice that consumes data from Mercado Libre and stores
    it in a database.
  title: Meli Microservice API
  version: "1.0"
paths:
  /:
    get:
      description: Entry point of the API
      produces:
      - application/json
      responses: {}
      summary: Root
      tags:
      - meta
  /api/v1/items:
    get:
      description: Get items from the database.
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Page size
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/core.Item'
            type: array
      summary: Get Items
      tags:
      - items
  /api/v1/process-file:
    post:
      description: Start the process of consuming data from Mercado Libre and storing
        it in a database.
      produces:
      - application/json
      responses: {}
      summary: Start Process
      tags:
      - process
  /api/v1/token:
    get:
      description: Get the API token to consume data from Mercado Libre.
      produces:
      - application/json
      responses: {}
      summary: Get API Token
      tags:
      - process
  /health:
    get:
      description: Health check of the API
      produces:
      - application/json
      responses: {}
      summary: Health Check
      tags:
      - meta
swagger: "2.0"
